### order1.json
POST http://localhost:8080/discount/strategy/2
Content-Type: application/json

{
  "id": "1",
  "customer-id": "1",
  "items": [
    {
      "product-id": "B102",
      "quantity": "10",
      "unit-price": "4.99",
      "total": "49.90"
    }
  ],
  "total": "49.90"
}
### order2.json
POST http://localhost:8080/discount/strategy/2
Content-Type: application/json

{
  "id": "2",
  "customer-id": "2",
  "items": [
    {
      "product-id": "B102",
      "quantity": "5",
      "unit-price": "4.99",
      "total": "24.95"
    }
  ],
  "total": "24.95"
}
### order3.json
POST http://localhost:8080/discount/strategy/2
Content-Type: application/json

{
  "id": "3",
  "customer-id": "3",
  "items": [
    {
      "product-id": "A102",
      "quantity": "1",
      "unit-price": "49.50",
      "total": "49.50"
    },
    {
      "product-id": "A101",
      "quantity": "2",
      "unit-price": "9.75",
      "total": "19.50"
    }
  ],
  "total": "69.00"
}
### order1a.json
POST http://localhost:8080/discount/strategy/2
Content-Type: application/json

{
  "id": "1",
  "customer-id": "1",
  "items": [
    {
      "product-id": "B102",
      "quantity": "10",
      "unit-price": "4.99",
      "total": "49.90"
    }
  ],
  "total": "1049.90"
}



